#!/bin/bash
# screen_tenant.sh
# Quick-start script — prints instructions for running tenant screening in Claude Code

echo ""
echo "================================================"
echo "  NYC Tenant Screening Toolkit"
echo "================================================"
echo ""
echo "To screen a new tenant, say the following in Claude Code:"
echo ""
echo "  'Please screen this tenant application using the"
echo "   tenant-screening skill. My requirements are in"
echo "   requirements.md. Monthly rent is \$2,600."
echo "   Here are their documents: [attach PDFs]'"
echo ""
echo "Documents to attach:"
echo "  - Bank statements (last 2-3 months)"
echo "  - Credit report"
echo "  - Pay stubs (last 2-3 months)"
echo "  - Tax returns (2023 and 2024)"
echo "  - Any landlord reference notes"
echo "  - Background check results"
echo ""
echo "Output: A structured report with APPROVE / DECLINE recommendation."
echo ""
echo "Templates available in /templates:"
echo "  - application-questionnaire.md  (send to applicants)"
echo "  - approval-letter.md"
echo "  - rejection-letter.md"
echo ""
echo "================================================"
